- name: BloodHound - Clone Repo into Tools directory
  git:
    repo: https://github.com/BloodHoundAD/BloodHound
    dest: "{{ ansible_env.HOME }}/tools/windows/BloodHound"

- name: BloodHound Tools - Clone Repo into Tools directory
  git:
    repo: https://github.com/BloodHoundAD/BloodHound-Tools
    dest: "{{ ansible_env.HOME }}/tools/windows/Bloodhound-Tools"
