- name: Install docker deps
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common

- name: Add Docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Save Debian version into a variable
  become: true
  shell: lsb_release -cs
  register: debian_version

- name: Add Docker repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_version.stdout }} stable"
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: "yes"
    force_apt_get: "yes"

- name: Install Docker
  become: true
  apt:
    name: "docker-ce"
    state: present
    force_apt_get: "yes"
