- name: Clone Findsploit repo
  git:
    repo: https://github.com/1N3/Findsploit.git
    dest: "/opt/Findsploit"
    force: yes

- name: install Findsploit
  shell: cd /opt/Findsploit; chmod +x install.sh; bash install.sh
