---
# tasks file for common
- name: Create non-root User  
  become: true
  user:
    name: pentest
    state: present
    groups: 'sudo'
    password: "{{ vault_pentest_password }}"
    shell: /bin/bash
    update_password: on_create

- name: Set authorized key taken from file
  authorized_key:
    user: pentest 
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Update repositories cache and install deps
  become: true
  apt:
    name:
      - ntp
      - git
      - fish
      - python2
      - python3
      - python-dev
      - python-crypto
      - curl
      - screen 
      - mosh
      - golang
      - pipenv
      - libxml2-dev 
      - libxslt1-dev
      - libssl-dev
      - libffi-dev
      - build-essential
      - unzip
    update_cache: yes

- name: Install common pen test tools and utilities through apt
  become: true
  apt:
    name:
      - dnsutils
      - masscan
      - nmap
      - dirb
      - dnsrecon

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart sshd

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart sshd

- name: Start SSH Server on boot
  become: true
  systemd:
    state: started
    enabled: yes
    name: ssh

- name: Start NTP Service on boot
  become: true
  systemd:
    state: started
    enabled: yes
    name: ntp

- name: Install penetration testing tools
  block:
    - include_tasks: pcredz.yml
    - include_tasks: responder.yml
    - include_tasks: crackmapexec.yml
    - include_tasks: docker.yml
    - include_tasks: impacket.yml
    - include_tasks: rubeus.yml
    - include_tasks: bloodhound.yml
    - include_tasks: pypykatz.yml
    - include_tasks: evil-winrm.yml
    - include_tasks: findsploit.yml
    - include_tasks: metasploit.yml
    - include_tasks: privesc.yml
    - include_tasks: shells.yml
    - include_tasks: sysinternals.yml
