- name: WindowsEnum - Clone WindowsEnum Repo into Tools directory
  git:
    repo: https://github.com/absolomb/WindowsEnum
    dest: "{{ ansible_env.HOME }}/tools/privesc/windows/WindowsEnum"

- name: JAWS - Clone JAWS Repo into Tools directory
  git:
    repo: https://github.com/411Hall/JAWS
    dest: "{{ ansible_env.HOME }}/tools/privesc/windows/jaws"

- name: pentestmonkey - Clone windows-privesc-check Repo into Tools directory
  git:
    repo: https://github.com/pentestmonkey/windows-privesc-check
    dest: "{{ ansible_env.HOME }}/tools/privesc/windows/windows-privesc-check"

- name: Linux Smart Enumeration - Clone repo into Tools directory
  git:
    repo: https://github.com/diego-treitos/linux-smart-enumeration
    dest: "{{ ansible_env.HOME }}/tools/privesc/linux/linux-smart-enumeration"

- name: PEAS - Clone privilege-escalation-awesome-scripts-suite Repo into Tools directory
  git:
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
    dest: "{{ ansible_env.HOME }}/tools/privesc/peass"

- name: Download pspy32
  get_url:
    url: https://github.com/DominicBreuker/pspy/releases/latest/download/pspy32
    dest: "{{ ansible_env.HOME }}/tools/privesc/linux/pspy32"
    mode: '0440'

- name: Download pspy64
  get_url:
    url: https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64
    dest: "{{ ansible_env.HOME }}/tools/privesc/linux/pspy64"
    mode: '0440'
