- name: ensure sysinternals directory exists
  file:
    path: "{{ ansible_env.HOME }}/tools/windows/sysinternals"
    state: directory

- name: Download and Unarchive Windows Sysinternals Suite
  unarchive:
    src: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: "{{ ansible_env.HOME }}/tools/windows/sysinternals"
    remote_src: yes
